apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  {{- include "namespace" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      {{- include "deploy-labels" . | indent 4 }}
  template:
    metadata:
      labels:
      {{- include "deploy-labels" . | indent 6 }}
    spec:      
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Values.image.repository }}
          ports:
            - containerPort: {{ .Values.image.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-mysql-secret
          livenessProbe:
            exec:
              command:
              {{- range .Values.executeCommand.steps }}
                - {{ . | quote }}
              {{- end }}